const UserRoutes = {
  ROOT_ROUTE: 'USER_ROUTE_ROOT',
  MAIN_SCREEN_ROUTE: 'USER_MAIN_ROUTE',
  STATUS_SCREEN_ROUTE: 'USER_STATUS_ROUTE',
  CONTACT_SCREEN_ROUTE: 'USER_CONTACT_ROUTE',
  PROFILE_SCREEN_ROUTE: 'USER_PROFILE_ROUTE',
};
export default UserRoutes;
